### ISSUE TITLE
pyamiibo seems to make amiibo register as "not an amiibo" when editing specific values.

### ISSUE THREAD

**Issue by Nozomuu** [tobywf/pyamiibo#1]
`with open('ML-Rob.bin', 'rb') as fp:
    dump = AmiiboDump(MASTER_KEYS, fp.read())

dump.unlock()
random_number = random.randint(0, 255)
dump.data[0x168+84] = random_number
random_number = random.randint(0, 255)
dump.data[0x169+84] = random_number
random_number = random.randint(0, 255)
dump.data[0x16a+84] = random_number
random_number = random.randint(0, 255)
dump.data[0x16b+84] = random_number
dump.lock()
dump.unset_lock_bytes()

with open('new.bin', 'wb') as fp:
    fp.write(dump.data)`

So this is how I'm editing specific bytes in the amiibo bin file, this is for smash ultimate, I have it randomizing between 0,255 and saving it to that value. The problem I seem to have is that it edited it correctly when I check it, but when I try to scan it in-game it comes back as "not an amiibo", would anyone be able to help me with this issue?

**Comment by tobywf** [comment]
Does it work when you don't modify the data?

**Comment by Nozomuu** [comment]
> Does it work when you don't modify the data?

When I open it and close it without modifying data it doesn't register as an amiibo either.

**Comment by Nozomuu** [comment]
> > Does it work when you don't modify the data?
> 
> When I open it and close it without modifying data it doesn't register as an amiibo either.

Quick update, when I remove dump.unset_lock_bytes(), it works fine if I just open it and close it without changing anything, but if I change any move values it still comes out as not an amiibo even without that.

**Comment by tobywf** [comment]
Great! It's been a while, I don't quite remember what `unset_lock_bytes` does. I think the idea was to write the tag, verify it, and then set the lock bytes, which is a non-reversible operation. To prevent blind copy & pasting from irreversibly writing tags, I may have left that in there.

As for the other bytes, I have no idea what those are or what effect writing them would be. The HMAC only depends on some parts of the data, and is recalculated on `lock()`. But random data may not be valid, or those offsets might be for dumps in the 3DS internal/amiitools layout, not the raw tag data. So I can't really help you much there unfortunately.
